Previous Homework
annapirova/mp-2023-pmi2 pull request #15
Opened 2023-10-17 22:50 UTC by KlozenSMA

Contains files 8-c, bools and cows and test files. I cannot upload 16-c now. i have problems with it. Today's homework in processing. Sorry for midnight uploading. Babkin Daniel.

2023-10-17 23:00 UTC, KlozenSMA commented
upd1: now contains guess the number

2023-10-17 23:31 UTC, KlozenSMA commented
upd2: added first file (exercise 20). Have an unknown error. Idk where I missed

2023-10-17 23:48 UTC, KlozenSMA commented
upd3: added 2-nd file(exercise 24). Working really strange but syntax is ok i think

2023-10-19 21:15 UTC, annapirova requested changes

2023-10-19 21:15 UTC, annapirova commented on Babkin/20-arrays.c
> +            for (j = i + 1; j < 100;j++)
здесь переделать алгоритм

2023-10-19 21:15 UTC, annapirova commented on Babkin/24-arrays.c
> +        if (comme == 1) {break;}
1) переделать условия в цикле так, чтобы было без break 
2) comme - бесполезная переменная, if (m[i] == m[j]) и if (comme == 1) {break;} можно объединить

2023-10-19 21:15 UTC, annapirova commented on Babkin/boolsncows.c
> +                z[a] = your_num % 10;
эту ветку надо убрать, весь процесс угадывания обернуть в цикл. Или убрать строки 20-44

2023-10-19 21:15 UTC, annapirova commented on Babkin/boolsncows.c
> +    int k[n],z[n];
поправить на константу

2023-10-19 21:15 UTC, annapirova commented on Babkin/boolsncows.c
> +                    printf("1");
надо считать угаданные позиции и не угаданные позиции. Просто распечатать мало.

2023-10-24 21:34 UTC, KlozenSMA commented on Babkin/20-arrays.c
> +            for (j = i + 1; j < 100;j++)
Доброй Ночи. Я немного переделал алгоритм, теперь вроде работает. Файл 20-arrays fix

2023-10-24 21:50 UTC, KlozenSMA commented on Babkin/24-arrays.c
> +        if (comme == 1) {break;}
Переделал файл. Проверял несколько раз. Вроде работает.

2023-10-27 14:45 UTC, annapirova commented
Даниил, у вас странные вложенные циклы.
Так: 
```
for (i)
        for (j = 0; i + j < 100; j++)
        {
            if ((m[i] == m[i+j]) && (j + i != i)) ///
}
```
не пишут.
Обычно внутренний цикл for (j = 0; j < 100; j++) или for (j = 0; j < i; j++)

2023-10-27 14:51 UTC, annapirova commented
Даниил, надо:
1) в быках и коровах переписать так, чтобы ветки else не было
```
 else
    {
        printf("Try again! \n");
        while (sum != n)
        {
}
```
переформулируйте условие во внешнем цикле

2) заменить задачу 24 на любую другую с номером >= 26

3) в 20й изменить странные циклы, убрать i+j < 100

2023-10-31 21:33 UTC, KlozenSMA commented
1. Я полностью переписал быков и коров. Оно работает почти нормально, за исключением того факта, что при вводе правильного ответа в первый раз, код выдаёт повтор последней строки. Со второго раза код выводит поздравления. Я не знаю с чем это может быть связано. Файл boolsncows[1].
2. Сделаю. 
3. Постараюсь поправить, но  вроде первый вариант с i + j < 100 работал нормально. Вы нашли какую то ошибку?

2023-10-31 21:35 UTC, KlozenSMA commented
Напомните ещё раз, когда крайний срок сдачи кассы? Я надеюсь не сегодня ведь?

2023-10-31 22:49 UTC, KlozenSMA commented
24 задача заменена на 28. Файл 28-arrays

2023-11-08 10:26 UTC, KlozenSMA commented
Долг по 16 задаче выше. Извините, что сейчас. Я всё слушаю и записываю. Файл 16-с[new].с Бабкин

2023-11-15 00:06 UTC, KlozenSMA commented
Добрый вечер я сделал кассу. Но она работает неправильно. Сейчас я не могу её переделать. Попробую завтра. И да. Я не знаю как создать новый пул реквест с нуля. Извините. Ещё вы не отметили замену 24 на 28. Когда я прочитал задачу с самстоятельной, то никаких видимых несостыковок я у себя не находил. Проверьте их прошу. Быки и коровы тоже здесь. Пожалуйста :(

2023-11-15 12:04 UTC, merged