Кочнева Вероника
annapirova/mp-2023-pmi2 pull request #16
Opened 2023-10-17 23:47 UTC by GothNika

Что-то тыкаю.. пытаюсь к вашему репозиторию подключиться :)

2023-10-19 14:03 UTC, annapirova requested changes
1) Переделать циклы в Быках-Коровах
2) переделать поиск повторов

2023-10-19 14:03 UTC, annapirova commented on Kochneva/mass_24.c
> +                    flag = 0;
зачем этот цикл? можно же сразу, когда нашли повтор, этот элемент как-то помечать.

2023-10-19 14:03 UTC, annapirova commented on Kochneva/cows and bulls.c
> +    while (1) {
переделать

2023-11-10 17:41 UTC, GothNika commented
исправила быков и коров

2023-11-13 13:59 UTC, annapirova commented
Ок

2023-11-13 13:59 UTC, merged