nikita ilyushkin
annapirova/mp-2023-pmi2 pull request #21
Opened 2023-10-25 09:50 UTC by s1ysoon

отправил задания быки и коровы угадайка и задание 1

2023-10-27 14:30 UTC, annapirova requested changes
исправить

2023-10-27 14:30 UTC, annapirova commented on Ilyushkin N/bulls and cows.c
> +	} while (gf == 0);
это выглядит странно. Надо упростить и переделать

2023-10-27 14:30 UTC, annapirova commented on Ilyushkin N/zad 1.c
> +
это присваивание, а не сравнение

2023-10-27 14:30 UTC, annapirova commented on Ilyushkin N/bulls and cows.c
> +		R[4] = 15;
а это зачем?

2023-11-08 09:32 UTC, s1ysoon reviewed
вот тут моя контрольная, я вам отправил её еще на паре, но почему то вы не увидели её, хотя мне говорили что она пришла и вы её  увидели...

2023-11-08 09:32 UTC, s1ysoon commented on Ilyushkin N/bulls and cows.c
> +		R[4] = 15;
я подумал что таким образом можно заменить массив с переменным размером...

2023-11-08 09:32 UTC, s1ysoon commented on Ilyushkin N/bulls and cows.c
> +	} while (gf == 0);
хорошо, я переделаю и отправлю.

2023-12-16 12:29 UTC, merged